import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  blobContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  blob: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(30, 123, 69, 0.3)',
  },
  glassHeader: {
    marginTop: 40,
    paddingTop: 20,
    paddingBottom: 16,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.26)',
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  titleContainer: {
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 12,
  },
  headerTitle: {
    fontFamily: 'Comfortaa',
    fontSize: 28,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  divider: {
    width: 128,
    height: 2,
    backgroundColor: '#FFFFFF',
    marginTop: 4,
  },
  profilePicture: {
    width: 49,
    height: 49,
    borderRadius: 25,
    overflow: 'hidden',
  },
  profileImage: {
    width: '100%',
    height: '100%',
  },
  houseId: {
    fontFamily: 'Comfortaa',
    fontSize: 14,
    fontWeight: '400',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  statsSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 24,
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#D9D9D9',
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  statLabel: {
    fontFamily: 'Comfortaa',
    fontSize: 11,
    color: '#000000',
    marginBottom: 8,
    textAlign: 'center',
  },
  statValue: {
    fontFamily: 'Comfortaa',
    fontSize: 20,
    fontWeight: '700',
    color: '#000000',
  },
  statUnit: {
    fontSize: 12,
    fontWeight: '400',
  },
  consumptionCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 16,
    marginTop: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.26)',
  },
  consumptionTitle: {
    fontFamily: 'Comfortaa',
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
  },
  timeLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  timeLabel: {
    fontFamily: 'Comfortaa',
    fontSize: 11,
    color: '#FFFFFF',
    opacity: 0.8,
  },
  sectionHeader: {
    paddingHorizontal: 16,
    marginTop: 32,
  },
  sectionTitle: {
    fontFamily: 'Comfortaa',
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  lightsCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.26)',
  },
  lightsGrid: {
    gap: 16,
  },
  lightItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  lightName: {
    fontFamily: 'Comfortaa',
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  lightSub: {
    fontFamily: 'Comfortaa',
    fontSize: 13,
    color: '#FFFFFF',
    opacity: 0.7,
    marginTop: 2,
  },
  routinesCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.26)',
  },
  routineRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  routineButton: {
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#D9D9D9',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  routineActive: {
    backgroundColor: '#649064',
  },
  routineText: {
    fontFamily: 'Comfortaa',
    fontSize: 14,
    fontWeight: '500',
    color: '#000000',
  },
  routineTextActive: {
    color: '#FFFFFF',
  },
  houseButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
    marginTop: 32,
    paddingHorizontal: 16,
  },
  houseButton: {
    backgroundColor: '#D9D9D9',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  houseButtonText: {
    fontFamily: 'Comfortaa',
    fontSize: 14,
    fontWeight: '500',
    color: '#000000',
  },
});